version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - acíclicos
  - Aleksandra
  - america
  - arxiv
  - BANIK
  - baselinestretch
  - bgcolor
  - biplot
  - boxplot
  - Boxplot
  - chatbots
  - chatrec
  - clusterización
  - cuantil
  - cuantiles
  - cuartil
  - cuartíl
  - cuartílico
  - deadpool
  - dfmpaper
  - didldfm
  - didlfm
  - dimensionalidad
  - dinámicamente
  - Douwe
  - escalabilidad
  - Escalabilidad
  - ésimo
  - Etran
  - Exhaustividad
  - Fabio
  - Fidelización
  - fontsize
  - framesep
  - Goyal
  - graficaron
  - Haofen
  - Harmsen
  - Heng
  - hiperparámetro
  - hiperparámetros
  - Huifeng
  - IDCG
  - ieee
  - interpretabilidad
  - Jiawe
  - Karpukhin
  - Keras
  - Kiela
  - Küttler
  - Levent
  - linenos
  - movielens
  - mpnet
  - multimodal
  - Naman
  - NDCG
  - NDGC
  - Ollama
  - otago
  - particionamiento
  - Petroni
  - Piktus
  - pixar
  - polinomial
  - Redoc
  - Rendle
  - Riedel
  - Rocktäschel
  - ROUNAK
  - Ruiming
  - serendípicas
  - serendipitosas
  - Sheng
  - Smola
  - sorpresivos
  - Steffen
  - TDMB
  - thiller
  - thor
  - tmdb
  - TMDB
  - tuplas
  - UNEXP
  - unimodal
  - wideanddeeppaper
  - Xiang
  - Xiong
  - Youlin
  - Yunfan
  - Yunming
  - Zhang
  - zhangdive
ignoreWords: []
import: []
